"""empty message

Revision ID: 1a0e90cd713a
Revises: 3191e136376b
Create Date: 2017-03-10 14:00:10.148621

"""

# revision identifiers, used by Alembic.
revision = '1a0e90cd713a'
down_revision = '3191e136376b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contact', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('User', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=True))
    op.alter_column('User', 'nickname',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.add_column('UserSocial', sa.Column('updated', sa.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSocial', 'updated')
    op.alter_column('User', 'nickname',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.drop_column('User', 'updated')
    op.drop_column('User', 'admin')
    op.drop_column('Contact', 'updated')
    ### end Alembic commands ###
