"""empty message

Revision ID: 1fcb5ae3ba67
Revises: 1a0e90cd713a
Create Date: 2017-03-10 14:31:32.948681

"""

# revision identifiers, used by Alembic.
revision = '1fcb5ae3ba67'
down_revision = '1a0e90cd713a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email_verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email_verified')
    ### end Alembic commands ###
