"""empty message

Revision ID: 24aef517d1d8
Revises: 2df0e272864b
Create Date: 2015-11-01 17:31:19.043596

"""

# revision identifiers, used by Alembic.
revision = '24aef517d1d8'
down_revision = '2df0e272864b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserInfo')
    op.add_column('User', sa.Column('about_me', sa.String(length=1023), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'about_me')
    op.create_table('UserInfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('about_me', sa.VARCHAR(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
