"""empty message

Revision ID: 2df0e272864b
Revises: 46db6058f4ae
Create Date: 2015-11-01 17:09:57.521453

"""

# revision identifiers, used by Alembic.
revision = '2df0e272864b'
down_revision = '46db6058f4ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserSocial', sa.Column('access_code', sa.String(length=2047), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSocial', 'access_code')
    ### end Alembic commands ###
