"""empty message

Revision ID: 3191e136376b
Revises: 27fb41592dbc
Create Date: 2017-03-10 13:35:05.061916

"""

# revision identifiers, used by Alembic.
revision = '3191e136376b'
down_revision = '27fb41592dbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'User_email_email_verification_token_removed_at_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['email', 'removed_at'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint(u'User_email_email_verification_token_removed_at_key', 'User', ['email', 'email_verification_token', 'removed_at'])
    ### end Alembic commands ###
